name: Create BOSH release

on:
  # Allows you to run this workflow manually from the Actions tab ONLY
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
          
      - name: Install BOSH CLI
        run: |
          set -euo pipefail
          echo "Installing bosh cli"
          curl -sSL $(curl -ksL "https://api.github.com/repos/cloudfoundry/bosh-cli/releases/latest" | jq -r '.assets[] | select(.name | contains("linux")) | .browser_download_url') --output bosh
          chmod +x bosh
          sudo mv bosh /usr/local/bin/bosh
          bosh -v
          
      - name: Vendor BOSH packages
        run: bosh vendor-package golang-1.17-linux ./src/golang-release
        
      - name: Build BOSH release tarball
        run: |
          set -euo pipefail
          VERSION=${{ steps.tag_version.outputs.new_version }}

          bosh create-release --final --version "$VERSION" --tarball "cloudgontroller-boshrelease-$VERSION.tgz"
          
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./cloudgontroller-boshrelease-*.tgz
          fail_on_unmatched_files: true
          body: ${{ steps.tag_version.outputs.changelog }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          
          
